### ISSUE TITLE
[AngularJS] Sección de Puestos 

### ISSUE THREAD

**Issue by FacuEt** [tbert12/LincedIn-TallerII-SharedServer#17]
Listado y acciones sobre los puestos.

**Comment by FacuEt** [comment]
- [x] Listado de actuales
- [x] Agregar uno nuevo.
- [x] Modificar uno existente.
- [x] Eliminar uno existente.

**Comment by juanmanuelbouvier** [comment]
- [x] Filtrar por categorias
